# Generated by Django 5.1.7 on 2025-09-01 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gpsdata',
            name='inside_geofence',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
