# Generated by Django 5.1.7 on 2025-09-18 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0004_geofence2_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Livestock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('device_id', models.CharField(max_length=100, unique=True)),
                ('animal_type', models.CharField(choices=[('cow', 'Cow'), ('sheep', 'Sheep'), ('goat', 'Goat'), ('chicken', 'Chicken'), ('pig', 'Pig'), ('other', 'Other')], default='cow', max_length=20)),
                ('breed', models.CharField(blank=True, max_length=50)),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='livestock', to='tracking.ownerprofile')),
            ],
        ),
    ]
