# Generated by Django 5.1.7 on 2025-09-23 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0006_alter_livestock_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='ownerprofile',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_photos/'),
        ),
    ]
